
export const Constants = Object.freeze({
    // Global Application Settings
    UNDEFINED: 'undefined',
    NEWLINE: '%0D%0A',
    DOUBLE_NEWLINE: '%0D%0A%0D%0A',

    DEFAULT_LOCALE: 'ZAR',
    DEFAULT_SEPARATOR: ',',
    FORMAT_DECIMAL: '1.2-2',

    CSV_FILE_FORMAT: 'text/csv;charset=utf-8;',
    CSV_EXTENSION: 'csv',
    TOKEN: 'token',
    EMPTY_GUID: '00000000-0000-0000-0000-000000000000',
    CURRENT_USER: 'currentUser',


    HTTP_NOT_FOUND: 404,
    HTTP_BAD_REQUEST: 400,
    HTTP_FORBIDDEN: 403,
    HTTP_CONFLICT: 409,


    // DATE
    TIME_FORMAT: 'HH:mm',
    DATE_FORMAT: 'YYYY-MM-DD',
    FORMAT_DATE: 'dd-mm-yyyy',  // TODO: Not correct Formatting
    FORMAT_TIME: 'HH:mm:ss',
    FORMAT_DATE_TIME: 'YYYY-MM-DD hh:mm:ss',

    FORMAT_FULL_DATE_SECONDS: 'DD MMMM YYYY hh:mm:ss',
    FORMAT_FULL_DATE_TIME: 'DD MMMM YYYY HH:mm',
    FORMAT_FULL_DATE: 'DD MMMM YYYY',
    FORMAT_ISO: 'YYYY-MM-DDTHH:mm:ss.000Z',

    DEFAULT_TIMEZONE_ID: 51,
    DEFAULT_TIMEZONE_BIAS: 120,
    DEFAULT_AM_TIME: '1899-01-01T00:00:00',

    // Numbers
    DEFAULT_INTEGER: '0',
    DEFAULT_DECIMAL: '0.00',

    DEFAULT_30_DAYS: 29,
    DEFAULT_7_DAYS: 7,
    DEFAULT_SINGLE_DAY: 1,
    DEFAULT_MONTHLY_DAYS: 31,
    DEFAULT_MONTHLY_WEEKS: 4,
    DEFAULT_YEARLY_DAYS: 366,
    DEFAULT_YEARLY_WEEKS: 52,
});
